#!/usr/bin/env bash
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}🚀 Building Protocol Buffers...${NC}"

PROTO_DIR="proto"
RUST_PROTO_DIR="rust/proto"
DART_LIB_DIR="lib/src"

# === Clean previous generated files ===
echo -e "${YELLOW}🧹 Cleaning previous generated files...${NC}"

# Clean Rust generated directory completely (build.rs will regenerate everything including mod.rs)
find "$RUST_PROTO_DIR" -name "*.rs" -type f -delete 2>/dev/null || true
mkdir -p "$RUST_PROTO_DIR"

# Create empty mod.rs placeholder (build.rs will overwrite it)
echo "// Placeholder - will be regenerated by build.rs" > "$RUST_PROTO_DIR/mod.rs"

# Clean Dart directory completely
rm -rf "$DART_LIB_DIR"/*.dart
mkdir -p "$DART_LIB_DIR"

# === Check protoc ===
if ! command -v protoc &> /dev/null; then
    echo -e "${RED}Error: protoc not installed${NC}"
    echo "Install: brew install protobuf"
    exit 1
fi

# === Compile Rust (using prost-build via build.rs) ===
echo -e "${YELLOW}⚙️  Compiling Rust with prost-build...${NC}"
cargo clean -q  # Ensure build.rs runs fresh
cargo build
RUST_COUNT=$(ls "$RUST_PROTO_DIR"/*.rs 2>/dev/null | wc -l | tr -d ' ')
echo -e "${GREEN}✓ Rust: ${RUST_COUNT} files generated (including mod.rs)${NC}"

# === Compile Dart ===
echo -e "${YELLOW}⚙️  Compiling Dart...${NC}"
if command -v protoc-gen-dart &> /dev/null; then
    PROTO_FILES=$(find "$PROTO_DIR" -name "*.proto")
    if [ -z "$PROTO_FILES" ]; then
        echo -e "${RED}Error: No .proto files found in $PROTO_DIR${NC}"
        exit 1
    fi

    protoc --dart_out="$DART_LIB_DIR" --proto_path="$PROTO_DIR" $PROTO_FILES
    DART_COUNT=$(ls "$DART_LIB_DIR"/*.dart 2>/dev/null | wc -l | tr -d ' ')
    echo -e "${GREEN}✓ Dart: ${DART_COUNT} files generated${NC}"

    # === Generate re-exports in lib/dig_proto.dart ===
    echo -e "${YELLOW}📦 Generating re-exports...${NC}"
    MAIN_LIB="lib/dig_proto.dart"

    cat > "$MAIN_LIB" << 'EOF'
/// Dig Project Protocol Buffer Definitions
///
/// This library contains auto-generated Protocol Buffer message definitions
/// for the Dig project.
///
/// ## Usage
///
/// Add this to your `pubspec.yaml`:
///
/// ```yaml
/// dependencies:
///   dig_proto:
///     path: ../dig-proto
/// ```
///
/// Then in your code:
///
/// ```dart
/// import 'package:dig_proto/dig_proto.dart';
///
/// void main() {
///   final user = User()
///     ..id = 'user-id'
///     ..name = 'John Doe';
/// }
/// ```

library;

// Export generated proto files
EOF

    # Add exports for all .pb.dart files (sorted alphabetically)
    for file in $(ls "$DART_LIB_DIR"/*.pb.dart 2>/dev/null | sort); do
        basename=$(basename "$file")
        echo "export 'src/$basename';" >> "$MAIN_LIB"
    done

    # Add re-exports of protobuf dependencies
    cat >> "$MAIN_LIB" << 'EOF'

// Re-export protobuf dependencies for convenience
export 'package:fixnum/fixnum.dart' show Int64;
export 'package:protobuf/protobuf.dart';
EOF

    EXPORT_COUNT=$(grep -c "^export 'src/" "$MAIN_LIB" 2>/dev/null || echo 0)
    echo -e "${GREEN}✓ Re-exports: ${EXPORT_COUNT} proto files exported in ${MAIN_LIB}${NC}"
else
    echo -e "${RED}Warning: protoc-gen-dart not found${NC}"
    echo "Install: dart pub global activate protoc_plugin"
    echo "Add to PATH: export PATH=\"\$PATH:\$HOME/.pub-cache/bin\""
fi

echo -e "${GREEN}✅ Done!${NC}"
echo ""
echo "Output directories:"
echo "  Rust: $RUST_PROTO_DIR/"
echo "  Dart: $DART_LIB_DIR/"
