// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(rust_macros::FromRequest)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Comment {
    #[prost(string, tag = "1")]
    pub resource: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub parent: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub body: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub user: ::core::option::Option<super::user::User>,
}
