// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(rust_macros::FromRequest)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Comment {
    #[prost(string, tag = "1")]
    pub resource: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub parent: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub body: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub user: ::core::option::Option<super::user::User>,
    #[prost(int32, tag = "6")]
    pub reply_count: i32,
    #[prost(message, optional, boxed, tag = "7")]
    pub replies: ::core::option::Option<::prost::alloc::boxed::Box<Comment>>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(rust_macros::FromRequest)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommentList {
    #[prost(string, tag = "1")]
    pub resource: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub parent: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "3")]
    pub comments: ::prost::alloc::vec::Vec<Comment>,
    #[prost(int32, tag = "4")]
    pub offset: i32,
    #[prost(int32, tag = "5")]
    pub total: i32,
}
