// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(rust_macros::FromRequest)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Comment {
    #[prost(string, tag = "1")]
    pub resource: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub parent: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub body: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub reply_count: i32,
    #[prost(message, repeated, tag = "7")]
    pub replies: ::prost::alloc::vec::Vec<Comment>,
    #[prost(int32, tag = "8")]
    pub created_at: i32,
    #[prost(int32, optional, tag = "9")]
    pub updated_at: ::core::option::Option<i32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(rust_macros::FromRequest)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommentList {
    #[prost(string, tag = "1")]
    pub resource: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub parent: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "3")]
    pub comments: ::prost::alloc::vec::Vec<Comment>,
    #[prost(map = "string, message", tag = "4")]
    pub users: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::user::User,
    >,
    #[prost(int32, tag = "5")]
    pub offset: i32,
    #[prost(int32, tag = "6")]
    pub total: i32,
    #[prost(int32, tag = "7")]
    pub limit: i32,
}
