// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(rust_macros::FromRequest)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Request {
    #[prost(string, tag = "1")]
    pub session: ::prost::alloc::string::String,
    #[prost(enumeration = "super::user::UserFrom", tag = "2")]
    pub from: i32,
    #[prost(string, tag = "3")]
    pub lng: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub ua: ::prost::alloc::string::String,
    #[prost(enumeration = "RequestKind", tag = "5")]
    pub kind: i32,
    #[prost(oneof = "request::Payload", tags = "6, 7")]
    pub payload: ::core::option::Option<request::Payload>,
}
/// Nested message and enum types in `Request`.
pub mod request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(rust_macros::FromRequest)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "6")]
        CommentRequest(super::super::comment::Comment),
        #[prost(message, tag = "7")]
        CommentListRequest(super::super::comment::CommentList),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(rust_macros::FromRequest)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RequestKind {
    None = 0,
    CommentAdd = 1,
    CommentEdit = 2,
    CommentDelete = 3,
    CommentList = 4,
    UserSync = 5,
}
impl RequestKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "NONE",
            Self::CommentAdd => "COMMENT_ADD",
            Self::CommentEdit => "COMMENT_EDIT",
            Self::CommentDelete => "COMMENT_DELETE",
            Self::CommentList => "COMMENT_LIST",
            Self::UserSync => "USER_SYNC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NONE" => Some(Self::None),
            "COMMENT_ADD" => Some(Self::CommentAdd),
            "COMMENT_EDIT" => Some(Self::CommentEdit),
            "COMMENT_DELETE" => Some(Self::CommentDelete),
            "COMMENT_LIST" => Some(Self::CommentList),
            "USER_SYNC" => Some(Self::UserSync),
            _ => None,
        }
    }
}
