// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(rust_macros::FromRequest)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ack {
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(string, optional, tag = "2")]
    pub detail: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(rust_macros::FromRequest)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Response {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(int32, tag = "2")]
    pub detail: i32,
    #[prost(oneof = "response::Payload", tags = "3")]
    pub payload: ::core::option::Option<response::Payload>,
}
/// Nested message and enum types in `Response`.
pub mod response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(rust_macros::FromRequest)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "3")]
        User(super::super::user::User),
    }
}
